### ISSUE TITLE
`VariablePrimal(N)` maybe should be `result_index` instead of `N`

### ISSUE THREAD

**Issue by Wikunia** [JuliaOpt/MathOptInterface.jl#1038] opened 2020-02-26 16:58 UTC
I think it would be cleaner to have `result_index` as the field name as it is the case for ObjectiveValue.
Currently it is `N` see:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/src/attributes.jl#L941-L951

Additionally in objective value it is referred to `ObjectiveValue(resultidx)` why not use either `resultidx` or `result_index` for both? I know this will break things but I think it would make it easier to read.

**Comment by odow** [comment] 2020-02-26 17:00
Closing as duplicate of #960

**Closed by odow** 2020-02-26 17:00 UTC
