### ISSUE TITLE
Rename `MultirowChange` to `MultirowLinearChange`

### ISSUE THREAD

**Issue by mohamed82008** [JuliaOpt/MathOptInterface.jl#410] opened 2018-06-30 07:16 UTC
It seems useful to support changing quadratic terms so why not change this to linear?

**Comment by odow** [comment] 2018-06-30 11:16
See also https://github.com/JuliaOpt/MathOptInterface.jl/pull/142

**Comment by mohamed82008** [comment] 2018-06-30 13:37
Interesting arguments there, but I am not suggesting removing "Multirow" just making it more clear, that is a "linear" change to each of the rows, just for clarity/verbosity.

**Comment by mohamed82008** [comment] 2018-07-22 10:08
Is this a welcome change in a PR or should I close the issue?

**Comment by mlubin** [comment] 2018-07-22 10:57
It's not clear that multirow change is even going to be used as it was intended for column generation. If we want to churn on this, we can just remove the modification instead.

**Comment by mohamed82008** [comment] 2018-07-22 11:29
Hmm ok I will see if it is not used elsewhere, then I will make a PR to remove it to trigger more discussion.

**Comment by odow** [comment] 2020-04-02 18:30
Closing since we're not going to change the name.

**Closed by odow** 2020-04-02 18:30 UTC
Labels: breaking
